// Generated by CoffeeScript 1.6.2
/*$(document).ready ->
	setInterval ->
		if (i) then $("#name").animate("opacity", "+=50%")
		if (!i) then $("#name").animate("opacity", "-+50%")
	, 200
*/


(function() {


}).call(this);
